### ISSUE TITLE
Testbed using of GLSL 4.00 when it's not needed.

### ISSUE THREAD

**Issue by Megaxela** [louis-langholtz/Box2D#39]
Testbed is using GLSL 4.00 but there is no any shaders or other parts of testbed that's using it for real. As for me I am getting an error, that GLSL 4.00 is not supported, cause supported versions are 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES. So when I'm changing code a little to change version of GLSL that would be used, everything is fine (I changed shader glsl `#version`).
```
glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
```

**Comment by louis-langholtz** [comment]
@Megaxela I may be confused then on what you mean.

The only place I see `glfwWindowHint` getting called now is in a pre-processor `#if defined(__APPLE__)` block. There it does specify major version 4. But this existing code should only be getting invoked on MacOS X systems.

Are you saying that `glfwWindowHint` also needs to be called for Linux systems but with the major set to 3? Is that because it defaults on Linux to trying to use version 4? Seems like if that's the case then this same issue should exist for Erin Cato's Box2D code too. Is that the case?

Thanks for assisting with this!

**Comment by Megaxela** [comment]
I guess that's true. It's not first machine that reproduces this error. I tried to remove `glfwWindowHint` calls, but even if i'll change shaders `#version` version, Testbed continue to proceed errors on shaders compilation. Yes, that issue exists in Erin Cato's Box2D repo. I remember that I changed this in his code to make it work.

**Comment by louis-langholtz** [comment]
Interesting!

Since the `glfwWindowHint` doesn't get called in the Testbed application for non-Apple systems, I believe the defaults would get used. According to the [online GLFW guide](http://www.glfw.org/docs/latest/window_guide.html#window_hints), that would be 1 and 0 then for the `GLFW_CONTEXT_VERSION_MAJOR` and `GLFW_CONTEXT_VERSION_MINOR` window hints respectively. Why then is the code trying to use GLSL 4.00 then on your system I'm wondering.

Googling "glsl 4.00 is not supported" reveals some possibly relevant info:

- [C++ OpenGL shading version error - GLSL x is not supported Ubuntu 16.04](https://stackoverflow.com/questions/40572941/c-opengl-shading-version-error-glsl-x-is-not-supported-ubuntu-16-04).
- [Shader can't be compiled](https://stackoverflow.com/questions/20931528/shader-cant-be-compiled).

Now I see that the shader programs in `DebugDraw.cpp` have `#version 400` in them while shader code in `RenderGL3.cpp` has `#version 150` in it. According to WikiPedia's [OpenGL Shading Language page](https://en.wikipedia.org/wiki/OpenGL_Shading_Language), these are some of the shader preprocessor choices and version 400 is from back in OpenGL 4.0 with a date of March 2010.

What does your system say if you run `sudo glxinfo | grep "OpenGL"`?

Regardless, I think I understand now what you were saying regarding the `#version` version. I wonder why version 400 was picked in Erin's code. Looks like he introduced a shader version in his commit 66252b58bbe8006bac1f01702b557f07de9aabde , wherein he has this version 400 already chosen.

I guess we need to understand or confirm what lowering the `#version` would do. Sounds like you're saying that version 400 isn't necessary and that older shader `#version` can be used. If you replace all occurrences of `#version 400` with `#version 330` does everything work then for you without doing any `glfwWindowHint` calls in the Testbed? My concern is that `glfwWindowHint` can set some settings in ways that can cause the runtime to fail instead of just overriding the "hint".

**Comment by Megaxela** [comment]
Ok, I tested Testbed without `glfwWindowHint`, and it didn't work. Still the same error, when it compiled shaders. If I'm only adding `glfwWindowHint` it's not working. If I'm only changing `#version` in shaders it's not working either.

**Comment by louis-langholtz** [comment]
@Megaxela Thanks for the update! I've changed the code now so that all of the Testbed shader programs request no more than `#version 330` (instead of `#version 400`) and so the hints given are always:

    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
    glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
    glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);

Crossing my fingers that this works better on your system and doesn't hurt on any others. When/if you get the chance, please try it out and let me know your results. Thanks!!

If this works better for you, I'm hoping we can get feedback from Erin Catto on why he picked `#version 400` to begin with. Would you be interested in filing an issue in his repo web pages for this? I was considering an issue subject like you used here.

**Comment by louis-langholtz** [comment]
I guess the changes worked and I see that Erin effectively took these changes to his repo as well. Nice to see this outcome. Closing this issue now.
