### ISSUE TITLE
Raycast is broken on some angles

### ISSUE THREAD

**Issue by Megaxela** [louis-langholtz/Box2D#40]
You can reproduce an error with testbed Ray-Cast test. It'll spend some triangle shapes.

**Comment by louis-langholtz** [comment]
Does it look like the ray cast isn't quite getting the edge of the shape? I think I committed code which increases the vertex radiuses without requiring the "skin" to also get drawn; so then it looks like the ray is not quite getting all the way that it should.

**Comment by louis-langholtz** [comment]
By the way, thank you for opening an issue for this, or any weirdness even that you may encounter. I really appreciate it!

**Comment by louis-langholtz** [comment]
Here's a zoomed in view of the ray-cast demo appearing to hit an edge and looking broken to me:
![screen shot 2017-05-15 at 8 40 17 pm](https://cloud.githubusercontent.com/assets/9611010/26087599/f2ac8334-39ae-11e7-9d8d-07d413d9c59d.png)

Here's the same zoomed in view but showing the "Skins" and now I see that it is actually hitting:
![screen shot 2017-05-15 at 8 42 17 pm](https://cloud.githubusercontent.com/assets/9611010/26087610/109a351c-39af-11e7-91b8-cff5bc9c3daa.png)

If this is what you're seeing, I think what I should do is augment the Testbed Test base code to give Test subclasses a way to modify options like enabling "Skins". Another option I'm considering is restoring the vertex radiuses of the edge segments to their original smaller setting so it's not as noticeable that ray-casting now factors in the vertex radius. A third and independent option that I may do is add an option for the ray-casting code to ignore the vertex radius.

What are your thoughts on these options?

**Comment by Megaxela** [comment]
That, what's i'm getting:
![image](https://cloud.githubusercontent.com/assets/1456504/26102816/7013784c-3a3f-11e7-815f-3d3d760a40e5.png)

**Comment by louis-langholtz** [comment]
Aha! Thank you for this picture. I can see the problem.

Turns out that the triangle shape created by pressing key '1' is meant to test the ray-cast method's ability to be instructed by its callback to ignore fixtures. There's documentation about this in the source code of `RayCast.hpp` file that runs this demo/test. There's no mention of this behavior though from the user's perspective on running the demo - the screen dumps show nothing being said to the user about this. That's definitely too hard to know for my taste. Sorry about this.

I'm working on a fix for this.

**Comment by Megaxela** [comment]
Ok, I tried to reproduce another strange error with this test and I guessed that I found undefined behaviour, but now, as you said, it's information issue I'll continue to trying to reproduce that bug. Thank you for fast reply

**Comment by louis-langholtz** [comment]
Here's how this looks now...

![screen shot 2017-05-16 at 7 02 35 pm](https://cloud.githubusercontent.com/assets/9611010/26134222/4a5fb194-3a6a-11e7-9f5d-adc760b93b60.png)

The difference being that the textual instructions on presses explain that pressing '1' results in a triangle "that should be ignored by the ray".

I also got rid of the enlarged vertex radiuses so that the skins are more normal sized now.
