### ISSUE TITLE
Possible RayCast bug, or help needed.

### ISSUE THREAD

**Issue by Megaxela** [louis-langholtz/Box2D#41]
I tried to implement some algorithm with using raycast, but I faced some strange problem.
https://drive.google.com/open?id=0B9qftqLpkN-iVWVKbDBEZUF4djQ

I'm using this code as callback:
```
class FirstCollisionResult : public box2d::RayCastFixtureReporter
{
public:
    FirstCollisionResult() :
            m_detected(false),
            m_point()
    {

    }

    virtual box2d::RealNum
    ReportFixture(box2d::Fixture *fixture,
                  const box2d::Length2D &point,
                  const box2d::UnitVec2 &normal,
                  box2d::RealNum fraction)
    {
        m_point = point;
        m_detected = true;
        return 0;
    }

    void reset()
    {
        m_detected = false;
        m_point = box2d::Length2D(0.0f, 0.0f);
    }

    bool isDetected() const
    {
        return m_detected;
    }

    box2d::Length2D point() const
    {
        return m_point;
    }

private:
    bool m_detected;
    box2d::Length2D m_point;
};
```

Now I'll try to implement this bug in testbed.

**Comment by Megaxela** [comment]
Ok, I figured out. It was my bad. I had to return `fraction` instread of `0`.

**Comment by louis-langholtz** [comment]
Glad to read that you figured out the problem.

Incidentally, the interface of `RayCastFixtureReporter` gets misunderstood more often than I like. It's basically the same still as in Erin's code base. I'm tempted to change it so that the `ReportFixture` method returns something else. I'd want that "something else" to be something that makes it easier to use correctly. If you have any thoughts on what you'd like that to look like, please let me know. I've opened issue #42 towards this.
